services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  admin.user.form.type:
      class: AdminBundle\Form\Type\UserType
      calls:
        - [setContainer, ['@service_container']]
      tags:
        - { name: form.type, alias: 'container_aware' }
