<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Survey;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySurvey(Survey $survey) {
        return $this->createQueryBuilder('c')
            ->where('c.survey = :s')
            ->orderBy('c.ordering')
            ->setParameter('s', $survey)
            ->getQuery()->getResult();
    }

    public function findByIdAndSurvey($id, Survey $survey) {
        return $this->createQueryBuilder('c')
            ->where('c.survey = :survey')
            ->andWhere('c.id = :id')
            ->setParameter('survey', $survey)
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
