<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Participant;
use AppBundle\Entity\Survey;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySurvey(Survey $survey) {
        return $this->createQueryBuilder('p')
            ->where('p.survey = :s')
            ->setParameter('s', $survey)
            ->getQuery()->getResult();
    }

    public function findBySurveyAndParticipant(Survey $survey, Participant $participant) {
        return $this->createQueryBuilder('p')
            ->where('p.survey = :s')
            ->andWhere('p.participant = :p2')
            ->setParameter('s', $survey)
            ->setParameter('p2', $participant)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
