<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Choice;
use AppBundle\Entity\Survey;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySurvey(Survey $survey) {
        return $this->createQueryBuilder('v')
            ->where('v.survey = :s')
            ->orderBy('v.participant')
            ->setParameter('s', $survey)
            ->getQuery()->getResult();
    }

    public function countBySurvey(Survey $survey) {
        return $this->createQueryBuilder('v')
            ->select('count(v.id)')
            ->where('v.survey = :s')
            ->setParameter('s', $survey)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
