app:
    resource: "@AppBundle/Controller/"
    type:     annotation
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Controller/UserController.php"
    type: annotation