services:
    user.form.type.honorary_choices:
        class: UserBundle\Form\Type\HonoraryChoicesType
        arguments:
            - '%honorary_choices%'
        tags:
            - { name: form.type }

    user.form.type.title_choices:
        class: UserBundle\Form\Type\TitleChoicesType
        arguments:
            - '%title_choices%'
        tags:
            - { name: form.type }

