services:
    app.text_type_extension:
        class: AppBundle\Form\Extension\TextTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }
    app.submit_type_extension:
        class: AppBundle\Form\Extension\SubmitTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\SubmitType }

    app.mailer:
        class: AppBundle\Service\Mailer
        arguments:
            - '@mailer'
            - '@templating'
            - '%editable.mailer_from%'
            - '%editable.mailer_from_alias%'